# Tools
AS      = nasm
LD      = ld
CC      = gcc

# Flags
ASFLAGS = -f elf
LDFLAGS = -T src/linker.ld -m elf_i386
CFLAGS  = -g -m32 -ffreestanding -O2 -Wall -Wextra -nostdinc -fno-builtin -fno-stack-protector -Isrc -Isrc/include -MMD -MP

# Paths
SRC     = src
BUILD   = build

# Auto-discover source files
C_SOURCES   = $(shell find $(SRC) -name '*.c')
ASM_SOURCES = $(shell find $(SRC) -name '*.asm')

# Generate object file paths (strip src/, add build/ prefix, change extension)
C_OBJECTS   = $(patsubst $(SRC)/%.c, $(BUILD)/%.o, $(C_SOURCES))
ASM_OBJECTS = $(patsubst $(SRC)/%.asm, $(BUILD)/%.o, $(ASM_SOURCES))
OBJECTS     = $(ASM_OBJECTS) $(C_OBJECTS)

# Dependency files (auto-generated by compiler)
DEPS = $(C_OBJECTS:.o=.d)

# Output
KERNEL = $(BUILD)/kernel.elf

# Default target
all: $(KERNEL)

# Link kernel
$(KERNEL): $(OBJECTS)
	$(LD) $(LDFLAGS) $^ -o $@

# Pattern rule: compile C files
$(BUILD)/%.o: $(SRC)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

# Pattern rule: assemble .asm files
$(BUILD)/%.o: $(SRC)/%.asm
	@mkdir -p $(dir $@)
	$(AS) $(ASFLAGS) $< -o $@

# Include auto-generated dependencies (header file changes)
-include $(DEPS)

# Run normally
run: $(KERNEL)
	qemu-system-i386 -kernel $(KERNEL) -m 64M -serial stdio 

# Run with GDB
run-debug: $(KERNEL)
	qemu-system-i386 -kernel $(KERNEL) -m 64M -serial stdio -nographic -s -S

# Clean build artifacts
clean:
	rm -rf $(BUILD)

# Show discovered files (useful for debugging Makefile)
show-files:
	@echo "C Sources:"
	@echo "$(C_SOURCES)" | tr ' ' '\n'
	@echo "\nASM Sources:"
	@echo "$(ASM_SOURCES)" | tr ' ' '\n'
	@echo "\nObjects:"
	@echo "$(OBJECTS)" | tr ' ' '\n'

# Phony targets (not actual files)
.PHONY: all run run-debug clean show-files
